//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCBelgium.DAO.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblCars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCars()
        {
            this.tblImages = new HashSet<tblImages>();
        }
    
        public int CarID { get; set; }
        public int BrandID { get; set; }
        [Display(Name="Model")]
        public string CarModel { get; set; }
        [Display(Name = "Prijs")]
        public double CarPrice { get; set; }
        [Display(Name = "Beschrijving")]
        public string CarDescription { get; set; }
        [Display(Name = "Uitrusting")]
        public string CarEquipment { get; set; }
        public int ColorID { get; set; }
        [Display(Name = "Bouwjaar")]
        public int CarYearOfConstruction { get; set; }
        [Display(Name = "Kilometerstand")]
        public int CarKilometers { get; set; }
        public byte Sold { get; set; }
        public string CarFuel { get; set; }
        [Display(Name = "Eerste inschrijving")]
        public System.DateTime FirstRegistration { get; set; }
        [Display(Name = "Vermogen KW")]
        public int PowerKW { get; set; }
        [Display(Name = "Vermogen PK")]
        public int PowerPK { get; set; }
        [Display(Name = "Cilindercapaciteit")]
        public int CylinderCapacity { get; set; }
        [Display(Name = "Transmissie")]
        public string Transmission { get; set; }
        [Display(Name = "CO2 uitstoot")]
        public string C02Emissions { get; set; }
        public System.DateTime Createdate { get; set; }
    
        public virtual tblBrands tblBrands { get; set; }
        public virtual tblColors tblColors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblImages> tblImages { get; set; }
    }
}
