//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCBelgium.DAO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImages
    {
        public int ImageID { get; set; }
        public int CarID { get; set; }
        public int ImageOrder { get; set; }
        public string ImagePath { get; set; }
    
        public virtual tblCars tblCars { get; set; }
    }
}
