//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCBelgium.DAO.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblPosts
    {
        public int PostID { get; set; }
        [Display(Name = "Titel")]
        public string PostTitle { get; set; }
        [Display(Name = "Beschrijving")]
        public string PostDescription { get; set; }
        [Display(Name = "Afbeelding")]
        public byte[] PostImage { get; set; }
        public System.DateTime PostDate { get; set; }
    }
}
