//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCBelgium.DAO.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblRimImages
    {
        public int ImageID { get; set; }
        public int RimID { get; set; }
        [Display(Name = "Afbeelding")]
        public byte[] Image { get; set; }
    
        public virtual tblRims tblRims { get; set; }
    }
}
