//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCBelgium.DAO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSlides
    {
        public int SlideID { get; set; }
        public string CaptionAlignment { get; set; }
        public string CaptionText { get; set; }
        public string CationColor { get; set; }
        public int SlideOrder { get; set; }
        public string ImagePath { get; set; }
    }
}
